version: 0.2
env:
  variables:
      BC_SOURCE: "codebuild"
      PRISMA_API_URL: "https://api.prismacloud.io"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
       - pip3 install bridgecrew
       - echo Installing codebuild-extras...
       - curl -fsSL https://raw.githubusercontent.com/bridgecrewio/aws-codebuild-extras/master/install >> extras.sh
       - . ./extras.sh
  build:
    commands:
      - checkov -d . --use-enforcement-rules --bc-api-key <key> --repo-id $CODEBUILD_ACCOUNT_ID/$CODEBUILD_PROJECT --branch $CODEBUILD_GIT_BRANCH -s -o cli -o junitxml --output-file-path console,test_results.xml
      - echo "Update AWS CLI"
      - pip3 uninstall -y awscli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - export PATH=$PATH:/usr/local/bin
      - echo "Install Kubectl"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - kubectl version --client
  post_build:
    commands:
      # Setup kubectl with our EKS Cluster              
      - echo "Update Kube Config"
      - export AWS_ACCESS_KEY_ID=""
      - export AWS_SECRET_ACCESS_KEY=""
      - export AWS_SESSION_TOKEN=""      
      - aws eks update-kubeconfig --name demo-eks-01
      - echo "Apply changes to kube manifests"
      - kubectl apply -f busybox-deployment.yaml
reports:
  bridgecrew-infrastructure-security:
    files:
       - test_results.xml
    discard-paths: yes
    file-format: JunitXml
